#############################################################################
# Makefile for building: ../out/brinespell
# Generated by qmake (3.1) (Qt 5.15.0)
# Project:  project.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile project.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_KEYWORDS -DMANA_WT -DQT_NO_DEBUG
CFLAGS        = -pipe -O2 -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -Wno-deprecated -Wno-write-strings -Wno-unused-result -Wno-format-security -O0 -std=gnu++1z -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../mana/mana -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = brinespell1.0.0
DISTDIR = /dalaran/brinespell/out/brinespell1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/dalaran/mana/out/ -lmana -lwthttp -lwt -lwtdbo -lwtdbomysql -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ../out/

####### Files

SOURCES       = main.cpp \
		config.cpp \
		test/unit_test.cpp \
		db/user.cpp \
		db/player.cpp \
		db/skill.cpp \
		db/campaign.cpp \
		broadcast.cpp \
		soma.cpp \
		soma_database.cpp \
		widget/wcontainer_nolayout.cpp \
		widget/wcontainer.cpp \
		widget/widget_login.cpp \
		widget/widget_search.cpp \
		widget/widget_audio.cpp \
		widget/widget_dice.cpp \
		widget/widget_chat.cpp \
		widget/widget_image.cpp \
		widget/widget_character.cpp \
		widget/widget_details_hp.cpp \
		widget/widget_stats.cpp \
		widget/widget_level.cpp \
		widget/widget_weapon.cpp \
		widget/widget_inventory.cpp \
		widget/widget_notes.cpp \
		widget/widget_home.cpp \
		thread/background.cpp 
OBJECTS       = ../out/main.o \
		../out/config.o \
		../out/unit_test.o \
		../out/user.o \
		../out/player.o \
		../out/skill.o \
		../out/campaign.o \
		../out/broadcast.o \
		../out/soma.o \
		../out/soma_database.o \
		../out/wcontainer_nolayout.o \
		../out/wcontainer.o \
		../out/widget_login.o \
		../out/widget_search.o \
		../out/widget_audio.o \
		../out/widget_dice.o \
		../out/widget_chat.o \
		../out/widget_image.o \
		../out/widget_character.o \
		../out/widget_details_hp.o \
		../out/widget_stats.o \
		../out/widget_level.o \
		../out/widget_weapon.o \
		../out/widget_inventory.o \
		../out/widget_notes.o \
		../out/widget_home.o \
		../out/background.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xlsx.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xlsx_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Qt5Keychain.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		project.pro config.h \
		test/unit_test.h \
		db/dbo_version.h \
		db/user.h \
		db/inventory.h \
		db/notes.h \
		db/player.h \
		db/skill.h \
		db/campaign.h \
		broadcast.h \
		soma.h \
		soma_database.h \
		widget/wcontainer_nolayout.h \
		widget/wcontainer.h \
		widget/widget_login.h \
		widget/widget_search.h \
		widget/widget_audio.h \
		widget/widget_dice.h \
		widget/widget_chat.h \
		widget/widget_image.h \
		widget/widget_character.h \
		widget/widget_details_hp.h \
		widget/widget_stats.h \
		widget/widget_level.h \
		widget/widget_weapon.h \
		widget/widget_inventory.h \
		widget/widget_notes.h \
		widget/widget_home.h \
		thread/background.h main.cpp \
		config.cpp \
		test/unit_test.cpp \
		db/user.cpp \
		db/player.cpp \
		db/skill.cpp \
		db/campaign.cpp \
		broadcast.cpp \
		soma.cpp \
		soma_database.cpp \
		widget/wcontainer_nolayout.cpp \
		widget/wcontainer.cpp \
		widget/widget_login.cpp \
		widget/widget_search.cpp \
		widget/widget_audio.cpp \
		widget/widget_dice.cpp \
		widget/widget_chat.cpp \
		widget/widget_image.cpp \
		widget/widget_character.cpp \
		widget/widget_details_hp.cpp \
		widget/widget_stats.cpp \
		widget/widget_level.cpp \
		widget/widget_weapon.cpp \
		widget/widget_inventory.cpp \
		widget/widget_notes.cpp \
		widget/widget_home.cpp \
		thread/background.cpp
QMAKE_TARGET  = brinespell
DESTDIR       = ../out/
TARGET        = ../out/brinespell


first: all
####### Build rules

../out/brinespell: /dalaran/mana/out/libmana.a $(OBJECTS)  
	@test -d ../out/ || mkdir -p ../out/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: project.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xlsx.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xlsx_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Qt5Keychain.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		project.pro
	$(QMAKE) -o Makefile project.pro -spec linux-g++
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KJS.pri:
/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt/mkspecs/modules/qt_KPty.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xlsx.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xlsx_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_Qt5Keychain.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
project.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile project.pro -spec linux-g++

qmake_all: FORCE


all: Makefile ../out/brinespell

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

../out/main.o: main.cpp soma.h \
		config.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		db/dbo_version.h \
		soma_database.h \
		../../mana/mana/database.h \
		test/unit_test.h \
		thread/background.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/yaml.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/main.o main.cpp

../out/config.o: config.cpp config.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		db/dbo_version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/config.o config.cpp

../out/unit_test.o: test/unit_test.cpp test/unit_test.h \
		config.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		db/dbo_version.h \
		db/user.h \
		db/campaign.h \
		db/player.h \
		db/inventory.h \
		db/notes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/unit_test.o test/unit_test.cpp

../out/user.o: db/user.cpp db/user.h \
		config.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		db/dbo_version.h \
		soma_database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/user.o db/user.cpp

../out/player.o: db/player.cpp db/player.h \
		config.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		db/dbo_version.h \
		db/user.h \
		db/inventory.h \
		db/notes.h \
		soma_database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/player.o db/player.cpp

../out/skill.o: db/skill.cpp db/skill.h \
		config.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		db/dbo_version.h \
		db/player.h \
		db/user.h \
		db/inventory.h \
		db/notes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/skill.o db/skill.cpp

../out/campaign.o: db/campaign.cpp db/campaign.h \
		config.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		db/dbo_version.h \
		db/player.h \
		db/user.h \
		db/inventory.h \
		db/notes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/campaign.o db/campaign.cpp

../out/broadcast.o: broadcast.cpp broadcast.h \
		config.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		db/dbo_version.h \
		soma.h \
		soma_database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/broadcast.o broadcast.cpp

../out/soma.o: soma.cpp soma.h \
		config.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		db/dbo_version.h \
		soma_database.h \
		db/user.h \
		db/campaign.h \
		db/player.h \
		db/inventory.h \
		db/notes.h \
		widget/widget_login.h \
		widget/wcontainer.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/wt/generic/widget_template.h \
		broadcast.h \
		widget/widget_home.h \
		widget/widget_search.h \
		widget/widget_audio.h \
		widget/widget_dice.h \
		widget/widget_chat.h \
		widget/widget_image.h \
		widget/widget_character.h \
		widget/widget_details_hp.h \
		widget/widget_level.h \
		widget/widget_stats.h \
		widget/widget_weapon.h \
		widget/widget_inventory.h \
		widget/widget_notes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/soma.o soma.cpp

../out/soma_database.o: soma_database.cpp soma.h \
		config.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		db/dbo_version.h \
		soma_database.h \
		db/user.h \
		db/player.h \
		db/inventory.h \
		db/notes.h \
		db/skill.h \
		db/campaign.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/soma_database.o soma_database.cpp

../out/wcontainer_nolayout.o: widget/wcontainer_nolayout.cpp widget/wcontainer_nolayout.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		soma_database.h \
		config.h \
		db/dbo_version.h \
		soma.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/wcontainer_nolayout.o widget/wcontainer_nolayout.cpp

../out/wcontainer.o: widget/wcontainer.cpp widget/wcontainer.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		soma_database.h \
		config.h \
		db/dbo_version.h \
		../../mana/mana/wt/generic/widget_template.h \
		broadcast.h \
		soma.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/wcontainer.o widget/wcontainer.cpp

../out/widget_login.o: widget/widget_login.cpp widget/widget_login.h \
		widget/wcontainer.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		soma_database.h \
		config.h \
		db/dbo_version.h \
		../../mana/mana/wt/generic/widget_template.h \
		broadcast.h \
		soma.h \
		db/user.h \
		db/campaign.h \
		db/player.h \
		db/inventory.h \
		db/notes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/widget_login.o widget/widget_login.cpp

../out/widget_search.o: widget/widget_search.cpp widget/widget_search.h \
		widget/wcontainer.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		soma_database.h \
		config.h \
		db/dbo_version.h \
		../../mana/mana/wt/generic/widget_template.h \
		broadcast.h \
		soma.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/widget_search.o widget/widget_search.cpp

../out/widget_audio.o: widget/widget_audio.cpp widget/widget_audio.h \
		widget/wcontainer.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		soma_database.h \
		config.h \
		db/dbo_version.h \
		../../mana/mana/wt/generic/widget_template.h \
		broadcast.h \
		soma.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/widget_audio.o widget/widget_audio.cpp

../out/widget_dice.o: widget/widget_dice.cpp widget/widget_dice.h \
		widget/wcontainer.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		soma_database.h \
		config.h \
		db/dbo_version.h \
		../../mana/mana/wt/generic/widget_template.h \
		broadcast.h \
		soma.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/widget_dice.o widget/widget_dice.cpp

../out/widget_chat.o: widget/widget_chat.cpp widget/widget_chat.h \
		widget/wcontainer.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		soma_database.h \
		config.h \
		db/dbo_version.h \
		../../mana/mana/wt/generic/widget_template.h \
		broadcast.h \
		soma.h \
		db/player.h \
		db/user.h \
		db/inventory.h \
		db/notes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/widget_chat.o widget/widget_chat.cpp

../out/widget_image.o: widget/widget_image.cpp widget/widget_image.h \
		widget/wcontainer.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		soma_database.h \
		config.h \
		db/dbo_version.h \
		../../mana/mana/wt/generic/widget_template.h \
		broadcast.h \
		soma.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/widget_image.o widget/widget_image.cpp

../out/widget_character.o: widget/widget_character.cpp widget/widget_character.h \
		widget/wcontainer.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		soma_database.h \
		config.h \
		db/dbo_version.h \
		../../mana/mana/wt/generic/widget_template.h \
		broadcast.h \
		soma.h \
		widget/widget_details_hp.h \
		widget/widget_level.h \
		widget/widget_stats.h \
		widget/widget_weapon.h \
		widget/widget_inventory.h \
		widget/widget_notes.h \
		db/player.h \
		db/user.h \
		db/inventory.h \
		db/notes.h \
		db/campaign.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/widget_character.o widget/widget_character.cpp

../out/widget_details_hp.o: widget/widget_details_hp.cpp widget/widget_details_hp.h \
		widget/wcontainer.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		soma_database.h \
		config.h \
		db/dbo_version.h \
		../../mana/mana/wt/generic/widget_template.h \
		broadcast.h \
		soma.h \
		db/player.h \
		db/user.h \
		db/inventory.h \
		db/notes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/widget_details_hp.o widget/widget_details_hp.cpp

../out/widget_stats.o: widget/widget_stats.cpp widget/widget_stats.h \
		widget/wcontainer.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		soma_database.h \
		config.h \
		db/dbo_version.h \
		../../mana/mana/wt/generic/widget_template.h \
		broadcast.h \
		soma.h \
		db/player.h \
		db/user.h \
		db/inventory.h \
		db/notes.h \
		db/skill.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/widget_stats.o widget/widget_stats.cpp

../out/widget_level.o: widget/widget_level.cpp widget/widget_level.h \
		widget/wcontainer.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		soma_database.h \
		config.h \
		db/dbo_version.h \
		../../mana/mana/wt/generic/widget_template.h \
		broadcast.h \
		soma.h \
		db/player.h \
		db/user.h \
		db/inventory.h \
		db/notes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/widget_level.o widget/widget_level.cpp

../out/widget_weapon.o: widget/widget_weapon.cpp widget/widget_weapon.h \
		widget/wcontainer.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		soma_database.h \
		config.h \
		db/dbo_version.h \
		../../mana/mana/wt/generic/widget_template.h \
		broadcast.h \
		soma.h \
		db/player.h \
		db/user.h \
		db/inventory.h \
		db/notes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/widget_weapon.o widget/widget_weapon.cpp

../out/widget_inventory.o: widget/widget_inventory.cpp widget/widget_inventory.h \
		widget/wcontainer.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		soma_database.h \
		config.h \
		db/dbo_version.h \
		../../mana/mana/wt/generic/widget_template.h \
		broadcast.h \
		soma.h \
		db/player.h \
		db/user.h \
		db/inventory.h \
		db/notes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/widget_inventory.o widget/widget_inventory.cpp

../out/widget_notes.o: widget/widget_notes.cpp widget/widget_notes.h \
		widget/wcontainer.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		soma_database.h \
		config.h \
		db/dbo_version.h \
		../../mana/mana/wt/generic/widget_template.h \
		broadcast.h \
		soma.h \
		db/player.h \
		db/user.h \
		db/inventory.h \
		db/notes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/widget_notes.o widget/widget_notes.cpp

../out/widget_home.o: widget/widget_home.cpp widget/widget_home.h \
		widget/wcontainer.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		soma_database.h \
		config.h \
		db/dbo_version.h \
		../../mana/mana/wt/generic/widget_template.h \
		broadcast.h \
		soma.h \
		widget/widget_search.h \
		widget/widget_audio.h \
		widget/widget_dice.h \
		widget/widget_chat.h \
		widget/widget_image.h \
		widget/widget_character.h \
		widget/widget_details_hp.h \
		widget/widget_level.h \
		widget/widget_stats.h \
		widget/widget_weapon.h \
		widget/widget_inventory.h \
		widget/widget_notes.h \
		db/campaign.h \
		db/player.h \
		db/user.h \
		db/inventory.h \
		db/notes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/widget_home.o widget/widget_home.cpp

../out/background.o: thread/background.cpp thread/background.h \
		../../mana/mana/mana.h \
		../../mana/mana/server.h \
		../../mana/mana/common.h \
		../../mana/mana/lib.h \
		../../mana/mana/win_dirent.h \
		../../mana/mana/mingw/mingw.mutex.h \
		../../mana/mana/mingw/mingw.thread.h \
		../../mana/mana/http.h \
		../../mana/mana/libcurl.arm/curl.h \
		../../mana/mana/libcurl.arm/curlver.h \
		../../mana/mana/libcurl.arm/curlbuild.h \
		../../mana/mana/libcurl.arm/curlrules.h \
		../../mana/mana/libcurl.arm/easy.h \
		../../mana/mana/libcurl.arm/multi.h \
		../../mana/mana/smtp.h \
		../../mana/mana/quickmail/quickmail.h \
		../../mana/mana/imap.h \
		../../mana/mana/cypher.h \
		../../mana/mana/polarssl/mbedtls/config.h \
		../../mana/mana/polarssl/mbedtls/check_config.h \
		../../mana/mana/polarssl/mbedtls/base64.h \
		../../mana/mana/polarssl/mbedtls/rsa.h \
		../../mana/mana/polarssl/mbedtls/bignum.h \
		../../mana/mana/polarssl/mbedtls/md.h \
		../../mana/mana/polarssl/mbedtls/threading.h \
		../../mana/mana/polarssl/mbedtls/sha1.h \
		../../mana/mana/ssh.h \
		../../mana/mana/daemon.h \
		../../mana/mana/parser.h \
		../../mana/mana/database.h \
		../../mana/mana/yaml.h \
		../../mana/mana/fuzzy.h \
		../../mana/mana/wt/wt.h \
		soma.h \
		config.h \
		db/dbo_version.h \
		soma_database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/background.o thread/background.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

